[package]
name = "sudograph"
version = "0.0.0"
authors = ["Jordan Last <jordan.michael.last@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sudodb = { path = "../sudodb" }
generate_graphql = { path = "./generate-graphql" }
async-graphql = "2.5.9"
getrandom = { version = "0.2.2", features = ["custom"] }
serde_json = "1.0.64"
serde = "1.0.123"
ic-cdk = { path = "../cdk-rs/src/ic-cdk", version = "0.2.1" }
ic-cdk-macros = { path = "../cdk-rs/src/ic-cdk-macros", version = "0.2.1" }