[package]
name = "sudograph"
version = "0.0.0"
authors = ["Jordan Last <jordan.michael.last@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sudodb = { path = "../sudodb" }
async-graphql = "2.5.9"
ic-cdk = { path = "../cdk-rs/src/ic-cdk", version = "0.2.1" }
ic-cdk-macros = { path = "../cdk-rs/src/ic-cdk-macros", version = "0.2.1" }
serde_json = "1.0.64"
serde = "1.0.123"
sudograph_generate = { path ="./sudograph_generate" }